[project]
name = "back"
version = "0.1.0"
description = "Scheduler Manager Backend API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "uvicorn[standard]>=0.38.0",
    "sqlmodel>=0.0.27",
    "sqlalchemy>=2.0.44",
    "psycopg[binary]>=3.2.13",
    "pydantic>=2.12.4",
    "httpx>=0.27.0",
    "black>=25.11.0",
    "isort>=7.0.0",
    "pylint>=4.0.3",
    "pytest>=7.4.0",
]

[tool.pylint.main]
init-hook = "import sys, os; sys.path.append(os.path.join(os.getcwd(), '..'))"
